api-homegar:
  email: '<login>'
  password: '<password>'

# Param pour les capteurs : température max à surveiller, cadence des alertes en heure
# exemple si alert-frequency est fixé à 24, la notification ne sera envoyée qu'une fois toutes les 24h en cas de dépassement
sensors:
  - name: 'extérieur '
    max-temperature: 40
    alert-frequency: 24
  - name: 'cage '
    max-temperature: 25
    alert-frequency: 18
  - name: 'congélo '
    max-temperature: -10
    alert-frequency: 24

azure-mail:
  connection-string: '<Azure communication email connection string>'
  sender: '<email sender address>'